"""message

Revision ID: 0caf4c978ac2
Revises: 97477565c35e
Create Date: 2024-07-09 21:49:56.381476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caf4c978ac2'
down_revision = '97477565c35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'img')
    # ### end Alembic commands ###
