"""message

Revision ID: 0fa6e9c243ff
Revises: a20c03123941
Create Date: 2024-07-21 20:51:00.146648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa6e9c243ff'
down_revision = 'a20c03123941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
