"""message

Revision ID: 1222674a4cdc
Revises: 85f33b14f190
Create Date: 2024-07-19 18:16:59.073079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1222674a4cdc'
down_revision = '85f33b14f190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
