"""message

Revision ID: 15c664abad14
Revises: ea8c7e2aa6f1
Create Date: 2024-07-24 11:11:23.670436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c664abad14'
down_revision = 'ea8c7e2aa6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
