"""message

Revision ID: 1b926793e4a7
Revises: abec167646c4
Create Date: 2024-07-17 21:41:47.289079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b926793e4a7'
down_revision = 'abec167646c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
