"""message

Revision ID: 1e51c102e932
Revises: 0dc5732ff421
Create Date: 2024-07-19 19:42:47.426128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e51c102e932'
down_revision = '0dc5732ff421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
