"""message

Revision ID: 230bb0bf3dba
Revises: 60aec0dc2947
Create Date: 2024-07-19 22:54:07.841841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230bb0bf3dba'
down_revision = '60aec0dc2947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
