"""message

Revision ID: 2340fec71eb9
Revises: 36710bc9a08c
Create Date: 2024-07-09 22:23:08.563519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2340fec71eb9'
down_revision = '36710bc9a08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Auctions', sa.Column('img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Auctions', 'img')
    # ### end Alembic commands ###
