"""message

Revision ID: 23ac7b5553e1
Revises: 26f5576a108a
Create Date: 2024-07-09 22:35:26.206140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ac7b5553e1'
down_revision = '26f5576a108a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
