"""message

Revision ID: 2874273bcd15
Revises: 734b98dc3f72
Create Date: 2024-07-21 20:28:31.004431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2874273bcd15'
down_revision = '734b98dc3f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
