"""message

Revision ID: 34ea14200e18
Revises: 5bd2e6aaeea6
Create Date: 2024-07-10 23:47:45.167400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ea14200e18'
down_revision = '5bd2e6aaeea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currently', sa.Float(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('first_bid', sa.Float(), nullable=False),
    sa.Column('number_of_bids', sa.Float(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('longtitude', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('normalised_description', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Posts_id'), 'Posts', ['id'], unique=False)
    op.drop_index('ix_Auctions_id', table_name='Auctions')
    op.drop_table('Auctions')
    op.drop_constraint(None, 'Bids', type_='foreignkey')
    op.create_foreign_key(None, 'Bids', 'Posts', ['auction_id'], ['id'])
    op.drop_constraint(None, 'Photos', type_='foreignkey')
    op.create_foreign_key(None, 'Photos', 'Posts', ['auction_id'], ['id'])
    op.add_column('auction_category', sa.Column('Post_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'auction_category', type_='foreignkey')
    op.create_foreign_key(None, 'auction_category', 'Posts', ['Post_id'], ['id'])
    op.drop_column('auction_category', 'auction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_category', sa.Column('auction_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'auction_category', type_='foreignkey')
    op.create_foreign_key(None, 'auction_category', 'Auctions', ['auction_id'], ['id'])
    op.drop_column('auction_category', 'Post_id')
    op.drop_constraint(None, 'Photos', type_='foreignkey')
    op.create_foreign_key(None, 'Photos', 'Auctions', ['auction_id'], ['id'])
    op.drop_constraint(None, 'Bids', type_='foreignkey')
    op.create_foreign_key(None, 'Bids', 'Auctions', ['auction_id'], ['id'])
    op.create_table('Auctions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('currently', sa.FLOAT(), nullable=False),
    sa.Column('buy_price', sa.FLOAT(), nullable=False),
    sa.Column('first_bid', sa.FLOAT(), nullable=False),
    sa.Column('number_of_bids', sa.FLOAT(), nullable=False),
    sa.Column('start', sa.DATETIME(), nullable=False),
    sa.Column('ends', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('longtitude', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.VARCHAR(), nullable=False),
    sa.Column('normalised_description', sa.VARCHAR(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Auctions_id', 'Auctions', ['id'], unique=False)
    op.drop_index(op.f('ix_Posts_id'), table_name='Posts')
    op.drop_table('Posts')
    # ### end Alembic commands ###
