"""message

Revision ID: 36710bc9a08c
Revises: 0caf4c978ac2
Create Date: 2024-07-09 22:01:35.473086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36710bc9a08c'
down_revision = '0caf4c978ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('img', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'img')
    # ### end Alembic commands ###
