"""message

Revision ID: 48904766050e
Revises: 9881c4eda494
Create Date: 2024-07-21 20:21:41.026146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48904766050e'
down_revision = '9881c4eda494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
