"""message

Revision ID: 4f657a3c3387
Revises: 30698b6614a5
Create Date: 2024-07-19 19:37:44.852748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f657a3c3387'
down_revision = '30698b6614a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
