"""message

Revision ID: 5bd2e6aaeea6
Revises: 23ac7b5553e1
Create Date: 2024-07-10 23:32:32.166457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd2e6aaeea6'
down_revision = '23ac7b5553e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
