"""message

Revision ID: 734b98dc3f72
Revises: c096bc5018f0
Create Date: 2024-07-21 20:27:44.640131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734b98dc3f72'
down_revision = 'c096bc5018f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
