"""message

Revision ID: 7360fc5cfb79
Revises: efc6767b04fa
Create Date: 2024-07-24 19:07:25.145112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7360fc5cfb79'
down_revision = 'efc6767b04fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
