"""message

Revision ID: 7b95f06c60b7
Revises: 7df47147a40a
Create Date: 2024-07-16 20:23:50.465853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b95f06c60b7'
down_revision = '7df47147a40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
