"""Add new column to table

Revision ID: 82c584599e7b
Revises: d6e783c50162
Create Date: 2024-07-15 22:14:25.749182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c584599e7b'
down_revision = 'd6e783c50162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
