"""message

Revision ID: 89a17c19983d
Revises: 7a1c28f7cdf2
Create Date: 2024-07-24 19:04:27.598301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a17c19983d'
down_revision = '7a1c28f7cdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
