"""message

Revision ID: 8ff60a923f74
Revises: 7360fc5cfb79
Create Date: 2024-07-24 19:14:44.987556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff60a923f74'
down_revision = '7360fc5cfb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
