"""message

Revision ID: 97477565c35e
Revises: 378a1d2d0c3b
Create Date: 2024-07-05 17:52:22.520654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97477565c35e'
down_revision = '378a1d2d0c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
