"""message

Revision ID: 9881c4eda494
Revises: 09b2b0d7b8f1
Create Date: 2024-07-21 20:21:12.871976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9881c4eda494'
down_revision = '09b2b0d7b8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
