"""message

Revision ID: a20c03123941
Revises: ef4e0b88fc11
Create Date: 2024-07-21 20:48:38.355586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20c03123941'
down_revision = 'ef4e0b88fc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
