"""message

Revision ID: a8fd3d52ecdd
Revises: c8aa27f75399
Create Date: 2024-07-29 13:14:28.972110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fd3d52ecdd'
down_revision = 'c8aa27f75399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
