"""message

Revision ID: ba39f53865c4
Revises: 230bb0bf3dba
Create Date: 2024-07-19 22:55:32.064973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba39f53865c4'
down_revision = '230bb0bf3dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
