"""message

Revision ID: e19757406f1c
Revises: f00e541f2c5c
Create Date: 2024-07-21 20:35:03.106113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19757406f1c'
down_revision = 'f00e541f2c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
