"""message

Revision ID: e9c8063d6cc3
Revises: 73419d39dde1
Create Date: 2024-07-19 23:23:28.896656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c8063d6cc3'
down_revision = '73419d39dde1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
