"""message

Revision ID: ea8c7e2aa6f1
Revises: 0fa6e9c243ff
Create Date: 2024-07-24 11:10:51.260712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8c7e2aa6f1'
down_revision = '0fa6e9c243ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('comments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'comments')
    # ### end Alembic commands ###
