"""message

Revision ID: ef4e0b88fc11
Revises: ece8adf236ae
Create Date: 2024-07-21 20:47:04.065562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4e0b88fc11'
down_revision = 'ece8adf236ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
