"""message

Revision ID: efc6767b04fa
Revises: 89a17c19983d
Create Date: 2024-07-24 19:06:08.697352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc6767b04fa'
down_revision = '89a17c19983d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
