"""message

Revision ID: f00e541f2c5c
Revises: e0625cc3dbf9
Create Date: 2024-07-21 20:30:36.899562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00e541f2c5c'
down_revision = 'e0625cc3dbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
