"""message

Revision ID: fd8af35b736d
Revises: 25657c13fd6e
Create Date: 2024-07-16 20:32:09.300170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8af35b736d'
down_revision = '25657c13fd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
